name: Deploy Client to Live Server (Bun)

on:
   push:
      branches:
         - main
      paths:
         - 'packages/client/**'

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout Code
           uses: actions/checkout@v3

         - name: Setup Bun
           uses: oven-sh/setup-bun@v1

         - name: Install Dependencies
           run: bun install

         - name: Build Admin App
           working-directory: packages/client
           run: bun run build

         - name: Setup SSH Agent
           uses: webfactory/ssh-agent@v0.8.3
           with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

         - name: Clean Remote Directory
           run: |
              ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
                "rm -rf /home/${{ secrets.SSH_USER }}/admin.rcnlagosisland.com/*"

         - name: Upload Build Files
           run: |
              scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} -r ./packages/client/dist/* \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/admin.rcnlagosisland.com/

         - name: Verify Deployment
           run: |
              ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
              ls -la /home/${{ secrets.SSH_USER }}/admin.rcnlagosisland.com/
              EOF
